on:
  release:
    types: [published]
  pull_request:
    branches: main
  workflow_dispatch:

name: qualification-report

jobs:
  qualification-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GSM_QC_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          use-public-rspm: true

      - name: qualification report trigger
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{secrets.GSM_QC_TOKEN}}
          repository: Gilead-BioStats/gsm.qc
          event-type: qualification
          client-payload: '{
          "GH_TOKEN": "${{ secrets.GSM_QC_TOKEN }}",
          "repository": "${{ github.repository }}",
          "release_tag": "${{ github.ref_name }}"
          }'
